/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as AnglesRouteImport } from './routes/angles'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as IndexRouteImport } from './routes/index'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnglesRoute = AnglesRouteImport.update({
  id: '/angles',
  path: '/angles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/angles': typeof AnglesRoute
  '/statistics': typeof StatisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/angles': typeof AnglesRoute
  '/statistics': typeof StatisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/angles': typeof AnglesRoute
  '/statistics': typeof StatisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advanced' | '/angles' | '/statistics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advanced' | '/angles' | '/statistics'
  id: '__root__' | '/' | '/advanced' | '/angles' | '/statistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRoute
  AnglesRoute: typeof AnglesRoute
  StatisticsRoute: typeof StatisticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angles': {
      id: '/angles'
      path: '/angles'
      fullPath: '/angles'
      preLoaderRoute: typeof AnglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRoute,
  AnglesRoute: AnglesRoute,
  StatisticsRoute: StatisticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
